spring.application.name=job-scheduler

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/job_scheduler
spring.datasource.username=postgres
spring.datasource.password=ayush1923
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# App
server.port=8080

# JWT (we'll use this later)
jwt.secret=your-super-secret-key-that-is-at-least-32-characters-long
jwt.expiration=86400000