spring.application.name=job-scheduler

# Database — reads from env var if set, falls back to local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/job_scheduler}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ayush1923}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${SERVER_PORT:8080}

# JWT
jwt.secret=${JWT_SECRET:your-super-secret-key-that-is-at-least-32-characters-long}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Springdoc
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.placements.job_scheduler
springdoc.pathsToMatch=/**

# Scheduling
spring.task.scheduling.pool.size=5
spring.security.filter.dispatcher-types=request,error,async


springdoc.swagger-ui.operationsSorter=method
spring.mvc.pathmatch.use-suffix-pattern=false
springdoc.default-produces-media-type=application/json
spring.websocket.max-text-message-size=65536

